### ISSUE TITLE
Windows Ledger gets wrong path?

### ISSUE THREAD

**Issue by rotlaus** [lifepillar/Ledger.tmbundle#4]
I've installed the extension on my windows machine. I've pointed the ledger.binary to the ledger executable ('C:\Users\adrian\bin\ledger.exe' in my case).

But i get the error message 
Error: Cannot read journal file "/cygdrive/c/Program Files/Microsoft VS Code/e:\Documents\Privat\journal.ledger"

I assume that error message comes from the ledger executable. It seems it gets the wrong path to the ledger file?

**Comment by lifepillar** [comment]
This repo contains an extension for TextMate, which AFAIK is a macOS-only text editor. Where did you install it under Windows? I have never tested this repo's code under Windows, so I don't expect it to work there.

**Comment by rotlaus** [comment]
Oh, i'm in the wrong project. Sorry. I installed it in Visual Studio Code via the extension manager. After rereading the description that extension is 'based on the Ledger.tmbundle file created by lifepillar'. 
I took a wrong turn there. Sorry for the confusion.
